name: 'severity-formula: Build and Deploy to GKE'

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-publish-deploy:
    runs-on: hacken-por
    permissions:
      contents: read
      id-token: write
    env:
      SERVICE_NAME: severity-formula
      REGISTRY: europe-west3-docker.pkg.dev/hacken-por/hacken-por
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/921687900132/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-ci-oidc@hacken-por.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

      - name: Build and Push
        run: |-
          docker build -f Dockerfile -t ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} -t ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:latest .
          docker push ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:latest

      - name: Deploy
        run: |-
          gcloud container clusters get-credentials por-prod --region europe-west3 --project hacken-por
          helm upgrade ${{ env.SERVICE_NAME }} ./helm -n audit-tools --create-namespace --force --install --wait --timeout 15m0s -f ./helm/prod.yaml --set image.repository=${{ env.REGISTRY }}/${{ env.SERVICE_NAME }} --set image.tag=${{ github.sha }} --debug
